name: Desktop Installer

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: '1.0.0'
      release_title:
        description: 'Title Release'
        required: false
      release_notes:
        description: 'Release Notes'
        required: false
        

jobs:
  build-pack:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish 
      run: |
          dotnet publish Iconizer/Iconizer.csproj `
            -c Release `
            --self-contained `
            -r win-x64 `
            -o publish
      shell: powershell

    - name: Install Velopack Tool
      run: |
          dotnet tool install -g vpk
      shell: bash

    - name: Create Velopack Release
      run: |
          vpk pack \
            -u Iconizer.App \
            -v ${{ github.event.inputs.version }} \
            -p publish \
            -e Iconizer.exe
      shell: bash
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.release_title != '' && github.event.inputs.release_title || format('Release v{0}', github.event.inputs.version) }}
        body: |
            ${{ github.event.inputs.release_notes }}
        files: |
            Releases/Iconizer.App-win-Portable.zip
            Releases/Iconizer.App-win-Setup.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Upload publish folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-folder
        path: publish

        
