name: .NET Core Desktop Debug Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022  # Usamos una imagen que incluye Visual Studio con WAP

    strategy:
      matrix:
        configuration: [Debug]

    env:
      Solution_Name: Iconizer.sln
      Wap_Project_Path: IconizerInstaller/IconizerInstaller.wapproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore packages for .csproj
      run: dotnet restore Iconizer/Iconizer.csproj

    - name: Restore packages for .wapproj 
      run: msbuild IconizerInstaller/IconizerInstaller.wapproj /t:Restore

    - name: Build WAP Project
      run: |
        msbuild $env:Wap_Project_Path /p:Configuration=${{ matrix.configuration }} /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
    - name: Publish Self-Contained
      run: dotnet publish Iconizer/Iconizer.csproj --configuration Debug --runtime win-x64 --self-contained true --output ./debug-build

