name: Build Iconizer App and Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      Configuration: Debug
      Solution_Name: Iconizer.sln
      Project_Path: Iconizer/Iconizer.csproj
      Wap_Project_Path: IconizerInstaller/IconizerInstaller.wapproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    
    - name: dotnet restore Iconizer.csproj
      run: dotnet restore ${{ env.Project_Path }}

    
    - name: msbuild restore WAP project
      run: msbuild ${{ env.Wap_Project_Path }} /t:Restore

    
    - name: Build WAP Installer
      run: |
        msbuild ${{ env.Wap_Project_Path }} ^
          /p:Configuration=${{ env.Configuration }} ^
          /p:AppxBundle=Always ^
          /p:UapAppxPackageBuildMode=StoreUpload

   
    - name: Publish self-contained .exe
      run: |
        dotnet publish ${{ env.Project_Path }} ^
          --configuration ${{ env.Configuration }} ^
          --runtime win-x64 ^
          --self-contained true ^
          --output ./debug-build

    
    - name: Upload Debug Executable
      uses: actions/upload-artifact@v4
      with:
        name: Debug-Self-Contained-Exe
        path: ./debug-build

    
    - name: Upload App Installer Package
      uses: actions/upload-artifact@v4
      with:
        name: Installer-Package
        path: |
          **/*.appxbundle
          **/*.appx
