name: .NET Core Desktop

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Develop]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Iconizer.sln                     # Replace with your solution name, i.e. MyWpfApp.sln.
      Project_Path: Iconizer/Iconizer.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-build

    - name: Publish
      run: dotnet publish ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-build --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Application-${{ matrix.configuration }}
        path: ./publish
